budget/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'budget'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('cash/', views.CashView.as_view(), name='cash'),
    path('admin/', views.adminView, name='admin'),
]

tour2019/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.BudgetView),
    path('admin/', admin.site.urls),
    path('budget/', include('budget.urls')),
]

budget/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime


class Band(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myblog:persons', kwargs={'pk': self.pk})


class Member(models.Model):
    band = models.ForeignKey(Band, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name + " - " + self.band.name


class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name + " - " + self.country.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=100)
    rate = models.FloatField(default=0.0)
    date = models.DateField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name + " (" + str(self.date) + ") = " + str(self.rate)


class Sign(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=1)

    def __str__(self):
        return self.name


class Money(models.Model):
    date = models.DateField(default=datetime.now, blank=True,  verbose_name='Дата')
    member = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, null=True,  verbose_name='ФИО')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE,  verbose_name='Валюта')
    city = models.ForeignKey(City, on_delete=models.CASCADE,  verbose_name='Город')
    sign = models.ForeignKey(Sign, on_delete=models.CASCADE,  verbose_name='Приход\Расход')
    amount_cur = models.FloatField(default=0.0, blank=True,  verbose_name='Сумма (в валюте)')
    comment = models.CharField(max_length=300, default='', blank=True,  verbose_name='Комментарий')

    def __str__(self):
        return self.sign.symbol + str(self.get_amount_ru()) + " руб. " + self.category.name + " в " + self.city.name

    def get_amount_ru(self):
        return float(round(self.currency.rate * self.amount_cur, 2))

    def get_date_of_row(self):
        return self.date.strftime("%d-%m-%y")

    def get_date(self):
        return self.date.strftime("%d/%m")

    def get_amount_cur(self):
        return str(self.amount_cur) + " " + self.currency.name

budget/views.py
from django.views import generic
from budget.models import Money
from .filters import MoneyFilter
from django.shortcuts import redirect
from django.db.models import Sum


class IndexView(generic.ListView):
    template_name = 'budget/index.html'

    def get_queryset(self):
        return Money.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        f_qs = MoneyFilter(self.request.GET, queryset=self.get_queryset())
        context['filter'] = f_qs

        amount_ru_sum = 0
        for money in f_qs.qs:
            amount_ru_sum += money.amount_cur * money.currency.rate
        context['amount_ru_sum'] = amount_ru_sum

        return context



class CashView(generic.ListView):
    template_name = 'budget/cash.html'

    def get_queryset(self):
        return Money.objects.filter(category__name='cash')



def adminView(request):
    response = redirect('/admin/')
    return response

tour2019/views.py
from django.shortcuts import redirect

def BudgetView(request):
    response = redirect('/budget/')
    return response

budget/templates/budget/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Тур 2019{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="/static/budget/bootstrap/css/bootstrap.css"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/budget/style.css" />
    <script  src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="/static/budget/bootstrap/js/bootstrap.js"></script>
    <script src="/static/budget/bootstrap/js/bootstrap.bundle.js"></script>

</head>
<body>

<!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'budget:index' %}">Тур 2019</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'budget:cash' %}">Cash</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'budget:admin' %}">Admin page</a>
              </li>
          </ul>
      </div>
    </nav>
    <div class="container">

    {% block body %}
    {% endblock %}


    </div>
</body>
</html>

budget/templates/budget/cash.html
{% extends 'budget/base.html' %}
{% block body %}
    <br/>
    <h3>CASH</h3>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p><br/>
    {% endif %}

    <div class="raw">
        <div class="col">
            <table class="table table-sm table-striped">
                <thead>
               <tr>
                    <th>Имя</th>
                    <th>Сумма</th>
                    <th>RUB</th>
                    <th>Дата</th>
                    <th>Группа</th>
                    <th>Комментарий</th>
                </tr>
                </thead>
                <tbody>
                {% for money in object_list %}
                <tr>
                    <td>{{ money.member.name }}</td>
                    <td>{{ money.get_amount_cur }}</td>
                    <td>{{ money.get_amount_ru }}</td>
                    <td>{{ money.get_date }}</td>
                    <td>{{ money.member.band.name }}</td>
                    <td>{{ money.comment }}</td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

    </div>
{% endblock %}

budget/templates/budget/index.html
{% extends 'budget/base.html' %}
{% load bootstrap %}

{% block body %}
    <br/>
    <h3>Blankenberge & Life on Venus Tour 2019 Expenses</h3>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p><br/>
    {% endif %}

    <div class="raw">
        <div class="col-6">
        <div class="accordion" id="filterAccordion">
            <div class="card">
                <div class="card-header" id="filterHeading">
                  <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="true" aria-controls="filterCollapse">
                      Скрыть\показать фильтр
                    </button>
                  </h2>
                </div>
                <div id="filterCollapse" class="collapse show" aria-labelledby="headingTwo" data-parent="#filterAccordion">
                  <div class="card-body">

                            <form method="get">
                                {{ filter.form|bootstrap }}
                                <button type="submit" class="btn btn-dark">Применить фильтры</button>
                            </form>
                            <br/>
                          <a href="{% url 'budget:index' %}">Очистить фильтр</a>
                    </div>
                  </div>
                </div>
            </div>
        </div>

        <div class="col">
            <table class="table table-sm table-striped">
                <thead>
                <tr>
                    <th>+\-</th>
                    <th>Категория</th>
                    <th>Дата</th>
                    <th>Сумма</th>
                    <th>RUB</th>
                    <th>Город</th>
                    <th>Комментарий</th>
                </tr>
                </thead>
                <tbody>
                {% for money in filter.qs %}
                <tr>
                    <td>{{ money.sign.symbol }}</td>
                    <td>{{ money.category.name }}</td>
                    <td>{{ money.get_date }}</td>
                    <td>{{ money.get_amount_cur }}</td>
                    <td>{{ money.get_amount_ru }}</td>
                    <td>{{ money.city.name }}</td>
                    <td>{{ money.comment }}</td>
                </tr>
                {% endfor %}
                {% if amount_ru_sum %}
                <tr id="rawSum">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>ИТОГО:</td>
                    <td>{{ amount_ru_sum }}</td>
                    <td></td>
                    <td></td>
                </tr>
                {% endif %}

                </tbody>
            </table>
        </div>

    </div>
{% endblock %}